# Generated by Django 3.2.7 on 2021-09-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
    ]
